title: Bits and Bytes

author:
  name: 'Vidya Bhandary'
  email: 'vidya.ga@gmail.com'

description: > # this means to ignore newlines until "show_excerpts:"
  Occassional technical posts on items that are too long to fit in 
  'Things I learned' (TIL).   Some 'how-to's. Technical Book Reviews.
  
show_excerpts: true # set to true to show excerpts on the homepage

# Build settings
theme: minima

# generate social links in footer
minima:
  social_links:
    twitter: vidya_bhandary
    github:  vidyabhandary
    linkedin: vidyabhandary
  
  skin: solarized-dark

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag

google_analytics: UA-173880651-1
